<a href="https://colab.research.google.com/github/Animeshcoder/AI/blob/main/Graph_from_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing required modules
import pandas as pd

In [2]:
file = pd.read_csv("graph.csv", low_memory = False)
print(file)

       numeric_id_1  numeric_id_2                         Unnamed: 2
0               NaN           4.0  {'weight': 0.0036496350364963502}
1               0.0          12.0   {'weight': 0.002105263157894737}
2               0.0          18.0   {'weight': 0.002347417840375587}
3               0.0          25.0   {'weight': 0.004210526315789474}
4               0.0          30.0   {'weight': 0.002105263157894737}
...             ...           ...                                ...
10218         304.0         273.0  {'weight': 0.0070921985815602835}
10219         304.0         328.0   {'weight': 0.009345794392523364}
10220         206.0         395.0   {'weight': 0.014388489208633094}
10221         264.0         124.0   {'weight': 0.011904761904761904}
10222          98.0           NaN                                NaN

[10223 rows x 3 columns]


A **graph** is a mathematical and pictorial representation of a set of vertices and edges. It consists of the non-empty set where edges are connected with the nodes or vertices. The nodes can be described as the vertices that correspond to objects. The edges can be referred to as the connections between objects.

A **directed** graph is a type of graph that contains ordered pairs of vertices while an **undirected** graph is a type of graph that contains unordered pairs of vertices. Thus, this is the main difference between **directed** and **undirected** graph2. In **directed** graphs, the edges represent the direction of vertexes.

In an **undirected** graph, the edges do not have a specific direction and it is **bidirectional** in nature it does not have a parent-child relation concept as there is no particular direction

In [3]:
# finding edges

dataset = []

# Iterate through the edges and check if they are bidirectional
for index, row in file.iterrows():
    # Get the two vertices connected by the edge
    vertex1, vertex2 = row['numeric_id_1'], row['numeric_id_2']
    dataset.append((vertex1, vertex2))

In [4]:
# Initialize a variable to store whether the graph is directed or not
is_directed = False
# Initialize a set to store the edges
edge_set = set()
for data in dataset:
  if (data[0], data[1]) not in edge_set:
    is_directed = True

  edge_set.add(data)

# Print whether the graph is directed or not
if is_directed:
    print('The graph is directed')
else:
    print('The graph is undirected')

print('No. of edges: ',len(edge_set))

The graph is directed
No. of edges:  10170


In [10]:
# finding vertices
vertices = pd.concat([file['numeric_id_1'], file['numeric_id_2']]).tolist()
size = len(set(vertices))

print("No. of vertices: ", size)

No. of vertices:  477


# **Adjacency List**
An adjacency list is a way to represent a graph using a collection of unordered lists. Each list within the adjacency list describes the set of neighbors of a particular vertex in the graph.

For example, consider a simple undirected graph with three vertices A, B, and C, and two edges (A, B) and (B, C). This graph can be represented using an adjacency list as follows:

A: B

B: A, C

C: B

In this representation, the first line indicates that vertex A is adjacent to vertex B. Similarly, the second line indicates that vertex B is adjacent to both vertices A and C.

In [8]:
# Initialize the adjacency dictionary
adj_list = {}
j = 0
# Iterate through the edges and update the adjacency dictionary
for i in range(len(dataset)-1):
    if dataset[i][0] == dataset[i+1][0]:
        if dataset[i][0] not in adj_list:
            adj_list[dataset[i][0]] = []
        adj_list[dataset[i][0]].append(dataset[i][1])
    else:
        if dataset[i][0] not in adj_list:
            adj_list[dataset[i][0]] = []
        adj_list[dataset[i][0]].append(dataset[i][1])
        j += 1

# Print the adjacency dictionary
print(adj_list)


{nan: [4.0], 0.0: [12.0, 18.0, 25.0, 30.0, 46.0, 55.0, 58.0, 59.0, 74.0, 76.0, 77.0, 85.0, 86.0, 87.0, 154.0, 168.0, 341.0, 374.0, 401.0, 11.0, 9.0, 38.0, 50.0, 27.0, 315.0, 29.0, 13.0, 33.0, 57.0, 71.0, 45.0, 202.0, 3.0], 4.0: [12.0, 14.0, 17.0, 24.0, 25.0, 27.0, 30.0, 46.0, 55.0, 58.0, 59.0, 64.0, 79.0, 84.0, 88.0, 89.0, 149.0, 154.0, 168.0, 179.0, 197.0, 213.0, 224.0, 243.0, 250.0, 268.0, 286.0, 293.0, 315.0, 374.0, 401.0, 447.0, 460.0, 77.0, 86.0, 87.0, 37.0, 50.0, 56.0, 16.0, 61.0, 71.0, 48.0, 53.0, 11.0], 12.0: [13.0, 17.0, 30.0, 32.0, 46.0, 55.0, 57.0, 59.0, 64.0, 74.0, 84.0, 89.0, 91.0, 126.0, 162.0, 254.0, 255.0, 327.0, 334.0, 392.0, 398.0, 448.0, 454.0, 470.0, 76.0, 85.0, 341.0, 21.0, 42.0, 68.0, 50.0, 14.0, 27.0, 26.0, 415.0, 54.0, 71.0, 422.0, 53.0, 379.0, 2.0], 18.0: [9.0, 14.0, 28.0, 42.0, 46.0, 50.0, 54.0, 55.0, 57.0, 59.0, 68.0, 79.0, 85.0, 110.0, 217.0, 229.0, 299.0, 442.0, 25.0, 74.0, 17.0, 89.0, 37.0, 73.0, 27.0, 26.0, 56.0, 61.0, 43.0, 48.0, 17.0], 25.0: [24.0, 27.0

In [7]:
# Initialize a dictionary to store the degree of each vertex
degree = {}

for data in dataset:
    # Increment the degree of the first vertex
    if data[0] not in degree:
        degree[data[0]] = 0
    degree[data[0]] += 1

    # Increment the degree of the second vertex
    if data[1] not in degree:
        degree[data[1]] = 0
    degree[data[1]] += 1

print(degree)

{nan: 1, 4.0: 46, 0.0: 33, 12.0: 43, 18.0: 32, 25.0: 59, 30.0: 54, 46.0: 59, 55.0: 53, 58.0: 59, 59.0: 55, 74.0: 46, 76.0: 38, 77.0: 47, 85.0: 38, 86.0: 37, 87.0: 82, 154.0: 60, 168.0: 18, 341.0: 54, 374.0: 59, 401.0: 91, 11.0: 34, 9.0: 46, 38.0: 23, 50.0: 54, 27.0: 58, 315.0: 91, 29.0: 23, 13.0: 30, 33.0: 30, 57.0: 30, 71.0: 104, 45.0: 19, 202.0: 52, 3.0: 47, 14.0: 36, 17.0: 95, 24.0: 53, 64.0: 47, 79.0: 43, 84.0: 45, 88.0: 45, 89.0: 52, 149.0: 75, 179.0: 91, 197.0: 68, 213.0: 20, 224.0: 37, 243.0: 28, 250.0: 19, 268.0: 61, 286.0: 44, 293.0: 46, 447.0: 38, 460.0: 53, 37.0: 36, 56.0: 31, 16.0: 34, 61.0: 57, 48.0: 28, 53.0: 47, 32.0: 59, 91.0: 38, 126.0: 77, 162.0: 46, 254.0: 142, 255.0: 42, 327.0: 69, 334.0: 10, 392.0: 26, 398.0: 17, 448.0: 38, 454.0: 21, 470.0: 44, 21.0: 30, 42.0: 26, 68.0: 37, 26.0: 59, 415.0: 32, 54.0: 71, 422.0: 67, 379.0: 38, 2.0: 39, 28.0: 21, 110.0: 26, 217.0: 30, 229.0: 60, 299.0: 43, 442.0: 59, 73.0: 48, 43.0: 21, 75.0: 25, 80.0: 38, 111.0: 120, 123.0: 10, 136

# **Adjacency Matrix**
An adjacency matrix is a square matrix used to represent a finite graph. The elements of the matrix indicate whether pairs of vertices are adjacent or not in the graph. In the special case of a finite simple graph, the adjacency matrix is a (0,1)-matrix with zeros on its diagonal1.

For example, consider a simple undirected graph with three vertices A, B, and C, and two edges (A, B) and (B, C). This graph can be represented using an adjacency matrix as follows:

      A B C

    A 0 1 0

    B 1 0 1

    C 0 1 0

In this representation, the first row and first column represent vertex A. The element in the first row and second column is 1, indicating that there is an edge between vertices A and B. Similarly, the element in the second row and third column is 1, indicating that there is an edge between vertices B and C.

In [12]:
import numpy as np
matrix = np.zeros((size, size))
print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
# Create a dictionary to store the edges
edges = {}
for edge in dataset:
    edges[edge] = 1

# Iterate through the edges and update the adjacency matrix
for i in range(unique):
    for j in range(unique):
        if (vertices[i], vertices[j]) in edges:
            matrix[i][j] = 1

# Print the adjacency matrix
print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
